### PR TITLE
tlg0551.tlg004-tlg0551.tlg006

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Checking in some of latest fixes to Appian Perseus headers.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5429)*

**Comment by lcerrato** [comment]
@AlisonBabeu 
Just a reminder that the edition label should equal the edition file title.
So if you adopt the Greek in the label that should carry over to the file title, too.

These Appian files may not be the best for the Greek as this is all upper case, and I use the normalized cases. I noticed a few transcription errors in this batch. It's hard because there aren't good normalized examples for these so the accentuation can be tricky.

If possible, we try to get the target link to the work page start, too.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5432)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5434)*

**Comment by AlisonBabeu** [comment]
Hey @lcerrato thanks for reviewing. I will ditch the Greek titles for now I was copying them from some OCR and if it has issues the last thing I want to do is introduce more errors.  I also had thought we had moved away from linking to the exact page with where a work starts in a digitized volume but I will update that for the relevant volumes and do that moving forward with the Appian files!

**Pull request merged**
