### PR TITLE
(greek_conversion) various Herodotus typos + tlg0062

### PR DESCRIPTION
**Pull request by lcerrato**
RK20230315 RK20230322 RK20230411 RK20230419
continued work on #1399

### CODE REVIEW

**Comment by lcerrato** [comment]
@AlisonBabeu 
This is volume 3 of Lucian

**Comment by lcerrato** [comment]
Needs CTS/header check

**Comment by lcerrato** [comment]
moving over file to fix https://github.com/PerseusDL/canonical_protected/issues/16

**Comment by lcerrato** [comment]
all changed files are ok

**Comment by AlisonBabeu** [comment]
Sorry @lcerrato just saw this as was knee deep in finishing presentation!

**Comment by lcerrato** [comment]
No problem. We can review in SV. I just wanted to move over the Aristotle for the email request.

**Pull request merged**
