### PR TITLE
(greek_conversion) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by lcerrato**
first pass converting tlg0613.tlg001.perseus-grc #1399 1399

### CODE REVIEW

**Comment by lcerrato** [comment]
@AlisonBabeu @jacobwegner 
We could use this PR as a test case for a release build. Just one file.

**Review by AlisonBabeu — APPROVED** [review]
hi @lcerrato this looks good.

**Comment by lcerrato** [comment]
Holding for build work.

**Comment by lcerrato** [comment]
I didn't mean to add to this, but since I did, I'll just continue.

**Pull request merged**
