### PR TITLE
Fix lt, gt entities in Xenophon.

### PR DESCRIPTION
**Pull request by scott-fleischman**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hi @scott-fleischman ,
Thanks for the incoming PR. Can I ask you one step more as you go on this one (I will not be the final merger, this will be @lcerrato ) ? Could you transform lt to <add> and gt to </add> ? That's obviously some critical apparatus information which we missed :)

**Comment by scott-fleischman** [comment]
@PonteIneptique could you clarify what you would like me to change them to? Your suggestion of what to change them to comes through only as a question mark. I'm not sure what they should be, whether `<corr>`, `<add>`, `<del>`, etc.

**Comment by PonteIneptique** [comment]
"oups", corrected my comment :+1:

**Comment by scott-fleischman** [comment]
Does the `<` and `>` always indicate `<add>`? It's in more files than Xenophon, including Sophocles, Athenaeus and Thucydides in the TEI epidoc format and Diogenes Laertius in the `<TEI.2>` format.

**Comment by PonteIneptique** [comment]
This is at least my reading of critical apparatus (References ? http://udallasclassics.org/maurer_files/APPARATUSABBREVIATIONS.pdf )

**Comment by lcerrato** [comment]
I think that this type of review needs to take place in a different pass, to confirm that `<add>` is indeed the correct markup.
This is really up to different reviewers, but I have been viewing the goals of the initial file conversion as being basic CTS compliance. 
There is a lot of deep editing and markup that can be done on Perseus texts and we need to clarify this in our documentation before asking others to take this on.
I think that a simple correction PR should be fine. As @scott-fleischman notes, this is not an issue limited to these files.

**Comment by lcerrato** [comment]
@scott-fleischman Don't feel obligated to delve into the meaning of the tags at this stage. We appreciate these corrections.

**Comment by lcerrato** [comment]
See also https://github.com/PerseusDL/canonical-greekLit/issues/238

**Pull request merged**
