### PR TITLE
(tlg0007.tlg077.perseus-grc1.xml) EpiDoc and CTS Conversion

### LINKED ISSUE #638: (tlg0007.tlg077.perseus-grc1.xml) EpiDoc and CTS Conversion
Claiming file for conversion work.

### PR DESCRIPTION
**Pull request by kcooper42**
Fix #638 
Edited file for EpiDoc and CTS compliance.

### CODE REVIEW

**Comment by kcooper42** [comment]
@lcerrato There were a few weird things with this file I did not know what to do with. First, in the scan all the speakers are in upper case letters however in the xml, there is <hi rend="uppercase"> around names (in lowercase). Is this okay? Or should the names be just changed to uppercase or marked with another type of tag, if so, which one?
Also, in the beginning of the first speech by Zeuxippus in the 3rd line (line 84 in the file), in the XML there is a </gap> however looking at the scan there does not seem to be anything missing or marked indicating a gap. This is the only occurrence of a gap in the file, so I commented it out as I was unsure why it was there and there was no clear reason for it.

**Comment by lcerrato** [comment]
@kcooper42 
This is not easy because the speakers span several sections.

In general you need a speaker tag and then you add a label to show how they appear in print. We also identify the speakers in the header. 

It's going to take me time to review this and provide examples.

**Comment by lcerrato** [comment]
Take a look at https://github.com/PerseusDL/canonical-greekLit/blob/master/data/tlg0059/tlg029/tlg0059.tlg029.perseus-grc2.xml

In the header, you identify the people in 

`<particDesc>`
		`<person><persName>Ζεύξιππος</persName></person>`
		`<person><persName>Μοσχίων</persName></person>`
	`</particDesc>`

Then, the `<p>` is followed by `<said who="#Μοσχίων"><label>ΜΟΣΧΙΩΝ.</label>` where the `#` is followed by the full name as written out in lowercase nominative with accents and the `<label>` is how it appears in the print. (all caps, no accents, followed by a period).  

You have to close each `<said>` in each div.

When the same speaker is still continuing in the next section, you have to use `rend="merge"` to restart the speaking. It looks like Zeuxippus starts speaking in section 2 and his speaking does not end but carries through the entire balance of the work. If that's correct, every subsequent section/paragraph needs to indicate that. 
`<p rend="indent"><said who="#Ζεύξιππος" rend="merge"><label>ΖΕΥΞΙΠΠΟΣ.</label>space`

This is going to be pretty messy.

You are right about the `<gap>` tag. That looks like an error. I'd remove it. 
I would also just uppercase (as above) not `rend="uppercase"`

The other thing is to watch the paragraphs.  In my review of the files I've been re-adding them. I didn't ask that you do this since it was an omission on the part of the original editors. Here it matters how we encode the first section with the multiple speakers because each speaker is a new paragraph.

`<div ...1>`
`<p rend="indent"><said who="#firstspeakername><label>NAME.</label>space greektext</said></p>`
`<p rend="indent"><said who="#secondspeakername><label>NAME.</label>space greektext</said></p>`
etc.

Does that make sense?

**Comment by kcooper42** [comment]
@lcerrato I've made the suggested changes, adding `<p rend="indent>` tags for each speaker's speech and using the said and label tags. I've also removed the gap and included the names of the speakers in the header. 

Also for future reference, do you want me to do the same formatting and tags for the speakers in english files (which don't have any special markup currently in the code except for separate paragraphs)?

**Comment by lcerrato** [comment]
Hi @kcooper42 
This looks great.
Yes, the same code needs to be in the English files. The labels should match what's on the page, which may vary. The initial markup done for these was incomplete. It was an easy thing for past editors to overlook — if you aren't familiar with the Greek you would just handle it like straight prose but we'd like to treat the dialogues as such even if this markup is somewhat messy (since EpiDoc is not really designed for this).

**Comment by kcooper42** [comment]
@lcerrato Okay sounds good, I'll add that to the english files. Also, will you want Beranadakis' name transliterated in the editor field for future files?

**Comment by lcerrato** [comment]
Hi @kcooper42 
Yes, I am working on regularizing his name to the English rendition as used in the Perseus Catalog (as opposed to the Latin Teubner uses). I can change these as I go but please fix if it comes to mind.

**Pull request merged**
