### PR TITLE
(tlg0008.tlg001.perseus-grc3.xml) Corrected OCR errors

### PR DESCRIPTION
**Pull request by aurelberra**

### CODE REVIEW

**Comment by aurelberra** [comment]
Fix https://github.com/PerseusDL/canonical-greekLit/issues/576

**Comment by lcerrato** [comment]
Hi @aurelberra 
Just a note.
There are many more such errors with these files. The goal is to integrate the collection at OGL/Digital Athenaeus (which is much improved) into the future releases of the Scaife Viewer.
https://github.com/OpenGreekAndLatin/athenaeus-dev
More and better corrections have been done on Digital Athenaeus than the files found here.
Thanks, as always, for the corrections.

**Comment by aurelberra** [comment]
Thanks @lcerrato!

I had forgotten about this other repo. The aim is in fact quite different, since the files include prefatory material, apparatus, indexes, etc. I am interested only in Kaibel's edition for now. If the text was fine, it would be possible to extract the relevant parts of the material, but I had seen and see again that some words or phrases have been lost in the correction process. The repo only put online the corrected results without scripts or raw data, 5 years ago. Do you think better data is or will be available? In the meanwhile, is it not a good idea to improve the Perseus/Scaife text?

**Comment by lcerrato** [comment]
@aurelberra 
Hi, since so many corrections have been made by Monica @monberti, we envisioned her editions being the primary versions moving forward in Scaife (and Perseus 5). That is why we have not prioritized any corrections to these files. Typically, the error rate produced by in house OCR is so high, we would have replaced these versions anew in the First 1k Greek workflow.
The size of the files and the high rate of corrections make it hard for us to thoroughly review the changes — particularly in the GitHub web GUI.
I'm certainly happy to have the changes. (One file per PR is always easier for us to manage.)
Thanks again.

**Comment by aurelberra** [comment]
Thank you, @lcerrato. I hope the files will be further improved, of course – and I do appreciate @monberti's work, with whom a student of mine is currently working in Leipzig!

**Pull request merged**
