### PR TITLE
(tlg0004.tlg001) file conversion and improvements

### LINKED ISSUE #1347: (tlg0004) EpiDoc and CTS conversion
conversion work

### PR DESCRIPTION
**Pull request by lcerrato**
fix #1347

### CODE REVIEW

**Comment by lcerrato** [comment]
@jacobwegner 
The release creation seems to have failed (or was skipped) here for some reason?
Looks like the testing was successful.

**Comment by jacobwegner** [comment]
@lcerrato I'll take a closer look later today and follow up soon.

**Comment by lcerrato** [comment]
@jacobwegner 
No rush. Just checking in as this is my first PR with the changes in place.

**Comment by jacobwegner** [comment]
@lcerrato Yes, I see that too.  Here's what is happening:

- We run the [run_hooktest](https://github.com/PerseusDL/canonical-greekLit/blob/cf90425e7bd3f710dab3e64ece7c23c1d210a708/.github/workflows/ci.yml#L11) job each time a push is made to a branch with an open pull request _or_ when a push is made to `master`
- The [create_release](https://github.com/PerseusDL/canonical-greekLit/blob/cf90425e7bd3f710dab3e64ece7c23c1d210a708/.github/workflows/ci.yml#L39) job only runs if `run_hooktest` succeeded, and only if it is the `master` branch.

So the check here in the PR is correct:

image

The `run_hooktest` and `create_release`  jobs are then triggered when the PR is merged into `master`:

image

https://github.com/PerseusDL/canonical-greekLit/actions/runs/3251535802/jobs/5336913867

**Comment by lcerrato** [comment]
@jacobwegner 
Thanks!

**Pull request merged**
