### PR TITLE
Changes for new build

### PR DESCRIPTION
**Pull request by sonofmun**
Do not merge until Bridget has updated the Perseids servers.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/1143)*

**Comment by lcerrato** [comment]
Thanks, @sonofmun do we need in canonical-latinLit, too?

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       -1 |

## Words

| Changed   | Status   |
|:----------|:---------|
| `fre`     | Deleted  |
| `UNK`     | +122877  |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.opp-fre1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/1254)*

**Comment by sonofmun** [comment]
@lcerrato Once this passes Travis, you can go ahead and merge it.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       -1 |

## Words

| Changed   | Status   |
|:----------|:---------|
| `fre`     | Deleted  |
| `UNK`     | +122877  |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.opp-fre1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/1273)*

**Pull request merged**
