### PR TITLE
tlg0059.tlg023_tlg036_and_first_English_translations

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Final Plato Greek files. Updated cts_xml,Greek titles and metadata.

### CODE REVIEW

**Comment by lcerrato** [comment]
@AlisonBabeu 
A few failures appear to have been introduced here.
tlg0059.tlg019.perseus-eng2.xml  
tlg0059.tlg021.perseus-eng2.xml  
tlg0059.tlg022.perseus-eng2.xml 
tlg0059.tlg024.perseus-eng2.xml 
tlg0059.tlg033.perseus-grc2.xml

**Comment by lcerrato** [comment]
`tlg0059.tlg019.perseus-eng2.xml	 fatal: The element type "biblStruct" must be terminated by the matching end-tag "</biblStruct>". [In (L53 C4)]

	tlg0059.tlg021.perseus-eng2.xml	 fatal: The element type "biblStruct" must be terminated by the matching end-tag "</biblStruct>". [In (L51 C5)]

	tlg0059.tlg022.perseus-eng2.xml	 fatal: The element type "biblStruct" must be terminated by the matching end-tag "</biblStruct>". [In (L49 C21)]

	tlg0059.tlg024.perseus-eng2.xml	 fatal: The element type "biblStruct" must be terminated by the matching end-tag "</biblStruct>". [In (L51 C5)]

	tlg0059.tlg033.perseus-grc2.xml	 error: element "biblStruct" not allowed here [In (L37 C17)],  error: element "biblStruct" incomplete [In (L51 C14)]`

**Comment by AlisonBabeu** [comment]
hi @lcerrato sorry for some reason I forgot to validate and must have been missing the final tag when I copied in theupdated bibliographic information. Thanks for fixing!

**Comment by lcerrato** [comment]
@AlisonBabeu  I think they all pass now?

**Review by lcerrato — APPROVED** [review]

**Pull request merged**
