### PR TITLE
(typos_errors) minor typos in various files

### PR DESCRIPTION
**Pull request by lcerrato**
tlg0007.tlg038.perseus-grc2.xml
tlg0016.tlg001.perseus-grc2.xml

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5150)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5161)*

**Comment by lcerrato** [comment]
fix #1244 et ak

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5163)*

**Comment by capitains-hook** [comment]
## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |       +2 |

*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5166)*

**Pull request merged**
