### PR TITLE
(tlg0086.tlg045.perseus-grc) CTS and EpiDoc conversion for issue #514

### PR DESCRIPTION
**Pull request by djwhittle**
@lcerrato I commented out a bunch of lines discussing the previous edits let me know if there is a better way to format this block of text.

### CODE REVIEW

**Comment by lcerrato** [comment]
@djwhittle Yes, convert them to change tags and order them from newest to oldest. Discard the Revision 1.1 (etc), the time stamps, and any `$Log` notations so

`+Revision 1.1  2011-01-01 21:59:46  gcrane`
 `+QUOTE tags added`
 `+DEL tags added`
 `+ADD tags added`
 `+GAP entities added`
becomes
`<change when="2011-01-01" who="crane">QUOTE tags added, DEL tags added, ADD tags added, GAP entities added</change>`

and 
`<date>31-Jan-00</date>`
 `<respStmt>`
 `<name>AEM</name>`
 `<resp>ed.</resp>`
 `</respStmt>`
 `<item>convert to P3` (Where the close item tag closes the entire old log) 

becomes
`<change when="2000-01-31" who="AEM">convert to P3</change>`

**Comment by lcerrato** [comment]
Fix #514

**Comment by lcerrato** [comment]
@djwhittle 
Gosh, Aristotle is a pain!

We had a couple of typos breaking this build. First, the file name had an extra zero in the second part. Second, there was an extra slash in the refsDecl pattern. 

Also, when I looked at the print, there are some chapters (?) in here that were not in the file. I added those but they appear to be more logical containers for this work than the Bekker pages, so I may wind up using these as default. This wasn't anything either of us would have known from looking at the file so it wasn't any kind of mistake. Fortunately it's a small text.

Thanks for fixing the change log. I know that's a chore.

**Comment by djwhittle** [comment]
@lcerrato I noticed the extra zero actually just this afternoon and I had just commit the file to travis, but I can't spot the extra slash in the refDecl! I just cancelled travis so I can correct the slash. Is there anyway you would be able to say where the extra slash is? I cant seem to spot it. And sorry perhaps it was a bad call to tackle the Aristotle I thought it would be helpful but it is proving to be more of a hassle than anything else!

**Comment by lcerrato** [comment]
@djwhittle 
Oh, gosh, I had already made the correction to the slash — it would be visible in the file diff. I was just merging and didn't know why another build had started.

**Comment by djwhittle** [comment]
All good I will just cancel the build! Sorry about that!

**Comment by lcerrato** [comment]
Looks like some of my other changes were lost. We need to revert to my last commit.

**Pull request merged**
