### PR TITLE
tlg0061 -- initial files

### PR DESCRIPTION
**Pull request by gregorycrane**
https://github.com/PerseusDL/canonical-greekLit/issues/1493

### CODE REVIEW

**Comment by gregorycrane** [comment]
Alison -- let's clean the metadata for these four files up quickly (if we can).

**Comment by lcerrato** [comment]
Note that there are failing metadata files here.

**Comment by lcerrato** [comment]
I do not see any version where the four metadata files passed?

**Comment by lcerrato** [comment]
I have left corrections in the current open PR for the failing files.

**Pull request merged**
