### PR TITLE
(tlg0004.001) Epidoc and CTS conversion

### PR DESCRIPTION
**Pull request by charhoughton**
Also changed sections from `milestones` to `divs,` as well as some other minor editing

### CODE REVIEW

**Comment by charhoughton** [comment]
fix #511

**Comment by lcerrato** [comment]
Hi @charhoughton 
Please change `<div type="edition" n="urn:cts:tlg0004.tlg001.perseus-grc2" xml:lang="grc">` to
`<div type="edition" n="urn:cts:greekLit:tlg0004.tlg001.perseus-grc2" xml:lang="grc">` in Greek file

Please change `<div type="translation" n="urn:cts:tlg0004.tlg001.perseus-eng2" xml:base="eng">` to `<div type="translation" n="urn:cts:greekLit:tlg0004.tlg001.perseus-eng2" xml:lang="eng">`in English file

Also, any tags such as `<hi rend='ital'>` or `<pb n='5'/>` should have double quotation marks.

**Comment by lcerrato** [comment]
Hi @charhoughton,
I am going to merge your work and then further refine in a separate pull.

I see a lot of stuff that it would have been good to have been tagged on during the conversion process. As these are large files, and did not originate at Perseus, they are atypical. When I wrote my doc, I wrote it for a specific subset of files, and these are not in that subset. So this was probably not a set of files I would have chosen, unfortunately.

As these are very large I cannot easily merge in more changes (or quickly make these fixes). Don't worry about further work on these files. 

Thanks!

**Comment by lcerrato** [comment]
On hold. Do not edit.

**Comment by charhoughton** [comment]
Actually just pushed a commit to Travis for this. I'll hold on the pull request, though.

**Comment by lcerrato** [comment]
working on this in separate workflow

**Pull request closed without merging**
