### PR TITLE
Ajout de la traduction française du nom de Theophrastus (Issue #19) tlg0093

### PR DESCRIPTION
**Pull request by AnZadykhina**
Excuser-moi, premier commit a été créé par erreur

### CODE REVIEW

**Comment by lcerrato** [comment]
@AnZadykhina 
Thank you for these additions.
We are choosing to resolve alternate names of authors and works via the Perseus Catalog records, not within the files themselves.
See for example
http://catalog.perseus.org/catalog/urn:cite:perseus:author.1394
http://catalog.perseus.org/catalog/urn:cite:perseus:author.579

**Comment by PonteIneptique** [comment]
Hey @lcerrato 
I am actually teaching git in class and taught them to do pull request on my fork, unfortunately, when you do a pull request from a fork of a fork, it goes right back to the original repository, which is this one.
Though, about the translation, with the new Perseus Scaife, aren't people from Eldarion using the Capitains metadata to pull the information the website and wouldn't it be interesting to push this information here ?

**Comment by lcerrato** [comment]
Hi @PonteIneptique 
There is a ton of information that could be added to all of the files including alternate names in multiple languages, alternate titles, etc. That is why the MODS and MADS files exist. 
I'm not sure why we would want to approach this manually as this would introduce inconsistencies, add bloat to the files, and duplicate all of the work being done on the catalog.  The original reason we started the catalog was in fact an alternate name/title finding system.  It also benefits from having a single point of review.
These changes wouldn't necessarily be captured in the catalog: we actually need to think about reverse engineering the catalog data at some point if we adopt this approach. 
In the short term, it might make sense to have this info for the experimental interfaces but doesn't seem to be the best practice as it stands now.

@AlisonBabeu has this been discussed in the context of the OGL work?

**Comment by AlisonBabeu** [comment]
Hi @lcerrato  and @PonteIneptique.  We have discussed this challenge of different language names for authors and work titles but in general have reached no settled conclusions as to how much data we want or need to have in the TEI XML or CTS files themselves.  

Since OGL largely has Greek and Latin files, we have largely used Latin names for authors and work titles, or sometimes defaulted to the English author name. In the cts files for textgroups I've tried to include both Latin and English name variants, but haven't gone much  further than that in all honesty.

We discussed a lot of these ideas at length in this issue (https://github.com/OpenGreekAndLatin/First1KGreek/issues/1014) but there really hasn't been any formal planning as yet as to how to possibly utilize the rich authority data for author names and in admittedly few cases work titles found in the Perseus Catalog within the OGL proper.

**Comment by lcerrato** [comment]
Perhaps if time allows I will bring this up at the next OGL meeting. All of this data is here, for instance:
http://catalog.perseus.org/catalog/urn:cite:perseus:author.579

**Comment by PonteIneptique** [comment]
Dear @lcerrato and @AlisonBabeu , maybe it would be interesting to know that the next version of the current `__cts__.xml` files will be DC based : https://github.com/Capitains/guidelines/blob/master/data/martial/__capitains__.xml

We are currently refining the draft on our end at the Ecole des chartes and the new draft RelaxNG schema should be out soon. Maybe it will interest you ?

One of the thing this should resolve in the future and might be interesting for Perseus : collections won't be necessarily by cts hierarchies (which could mean you use either cite URN or viaf identifier).

**Comment by PonteIneptique** [comment]
Oh and someone from Eldarion, @brosner, whished to be part of the discussions ;)

**Comment by lcerrato** [comment]
Hi @PonteIneptique 
I can assure you that we meet regularly with Eldarion and we are working on major revisions to the catalog data. 
At this phase of work having two sets of information in two places that don't draw from each other doesn't seem like an ideal approach to me and something that can be resolved with a more sophisticated system. As the current editor of the repo, I think I would like to consider this in the context of all of this work. 

I spend lots of time cleaning up inconsistencies in our data and this is a major concern to me. Please respect the fact that I want some time to think about this and put in place a system to ensure that work being done on the data in the catalog is reincorporated into the cts environment so that we don't add to the text issues we have now. 

Thanks.

**Comment by PonteIneptique** [comment]
Hi @lcerrato ,
When I meant someone from eldarion wished to be part of the discussion, I meant about the new capitains guidelines, not this exact one. Sorry for the *qui pro quo* here.
I do not want to force this on you. That was not my intention.

**Pull request closed without merging**
