### PR TITLE
Replace Travis CI builds with GitHub Actions

### PR DESCRIPTION
**Pull request by jacobwegner**
@lcerrato had asked me to look into failures with the Travis CI builds.

I took a look at what had been done in https://github.com/OpenGreekAndLatin/Latin/commit/9a3e833b515adad490bdd11977eaf1a84d24b246 and adapted it to mimic the current build behavior:

- The `Hooktest and Release` workflow runs on all PRs and pushes to the default branch (`master`)
- Only pushes to `master` create releases

An example release can be seen at:

https://github.com/jacobwegner/canonical-greekLit/releases/tag/0.0.2821198127

## To Discuss:
- [x] I saw that the `--txt` flag has been used in Travis CI; the passing files are made available under the `text/` output.

Is that something we want to maintain going forward?  I've left it on for now, just thought it'd be worth calling out.

e.g.
- https://github.com/PerseusDL/canonical-greekLit/blob/6f64d82bdc45e4e938e0a25cd6661331d62f7173/text/tlg0012.tlg001.perseus-grc2.txt
- https://github.com/jacobwegner/canonical-greekLit/blob/c5330c63e11c235f3ff8f32c4571b32a86855c08/text/tlg0012.tlg001.perseus-grc2.txt

### CODE REVIEW

**Comment by jacobwegner** [comment]
@lcerrato Please take a look and let me know if you have any questions.  

Once we get this sorted out, I can send PRs from https://github.com/jacobwegner/csel-dev and https://github.com/jacobwegner/canonical-latinLit that mimic this PR.

**Comment by lcerrato** [comment]
@jacobwegner 
Yes, to the plain text creation. I point users to this quite often.
Thank you for this, I'll take a closer look tomorrow.

**Comment by lcerrato** [comment]
@jacobwegner I'm working in this repo now, so if you want to go ahead, this will give me a chance to see things in action and give feedback then. I think this is going to be fine. Thanks.

**Comment by jacobwegner** [comment]
@lcerrato: Sounds good!  I'm done with the branch from my work if y ou want to add a review and merge it in here:

image

**Review by lcerrato — APPROVED** [review]

**Pull request merged**
