### PR TITLE
tlg0003_all_files

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Updated a number of URNs from deu to ger for consistency. Changed OPP URNs to 1st1K.
Other minor edit.s

### CODE REVIEW

**Comment by lcerrato** [comment]
@AlisonBabeu 
I have a silly question. It looks like there is mostly "deu" for German throughout this collection versus "ger" appearing only once. So in the body of most works, the default is the former.  In development, there are over >1400 instances of deu versus 191 of ger.

**Comment by AlisonBabeu** [comment]
hey @lcerrato, do you mean deu to in language tagging? The only "ger" I changed here was to the URNs and the XML:BASE to be consistent across the collection,not language tagging itself. I've stuck with "deu" for the Unicode language tag.

**Comment by lcerrato** [comment]
@AlisonBabeu Yes, I was wondering why the URNs use ger when deu is the default elsewhere. Seems like we should choose one.

**Comment by AlisonBabeu** [comment]
I changed these from "deu" to ger because we had used "ger" in other 1st1K translations.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Do you think the file tags should read "ger" as well?

**Review by lcerrato — APPROVED** [review]

**Comment by lcerrato** [comment]
This needs to be fixed so that I can resolve https://github.com/PerseusDL/canonical-greekLit/pull/1474 which was closed (and subsequently closed the issue it was supposed to fix). So we have a "fixed" issue that is not actually fixed.
I have to manually add changed because of the subsequent conflicts I think.
Not sure what happened.

**Pull request merged**
