### PR TITLE
Update tlg0003.tlg001.perseus-eng6.xml

### PR DESCRIPTION
**Pull request by lcerrato**
See #1472

### CODE REVIEW

**Comment by lcerrato** [comment]
8 changes have been checked in

1. 1.11.3
2. 1.38.6
3. 1.65.3
4. 1.110.5
5. 3.3.6
6. 3.40.8
7. 3.85.4
8. 4.102.4

**Comment by lcerrato** [comment]
Should be 8;917;3587 in book/chapter/section count

**Review by AlisonBabeu — COMMENTED** [review]
hi @lcerrato I'm a little confused here. The pull request lists a number of sections added and refers to an issue that describes missing Greek sections of text It looks like what was done here was correction of the tagging in some English translation text?

**Review by AlisonBabeu — APPROVED** [review]
This looks good.

**Pull request merged**
