### PR TITLE
tlg0062.tlg042-tlg051

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Lasted cts and metadata revisions.

### CODE REVIEW

**Review by lcerrato — APPROVED** [review]
Note that the publication info for Perseus files is rendered differently and should include the release info.
```
<publisher>Trustees of Tufts University</publisher>
<pubPlace>Medford, MA</pubPlace>
<authority>Perseus Digital Libary Project</authority>
<date type="release" when="2007" cert="medium">Perseus 4.0</date>
<idno type="filename">tlg0627.tlg003.perseus-grc2.xml</idno>

```

This is not reflected in these files.

**Comment by lcerrato** [comment]
Note there are inconsistencies (Perseus Digital Library Project vs Perseus Project) everywhere, but this is closer. 

```
<publisher>Trustees of Tufts University</publisher>
<pubPlace>Medford, MA</pubPlace>
<authority>Perseus Project</authority>
    <date type="release" when="2023-06-23">Perseus 5.0</date>
    <idno type="filename">tlg0062.tlg055.perseus-grc3.xml</idno>
```

**Comment by AlisonBabeu** [comment]
hi @lcerrato I have been focused on bibliographic metadata correction and other inconsistencies. I figure I will do a few global changes such as review of publication statements when I do a final pass over Lucian.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Yes, that's why I approved. Just noting something I spotted here. (This isn't exclusive to these files, but it just caught my eye).

**Pull request merged**
