### PR TITLE
tlg0551.tlg001-.tlg0551.tlg002-perseus-eng2

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Updated CTS files to include more standardized titles and descriptions.

Updated bibliographic information to include more detail and link to source file.

@lcerrato also one question. For the CTS file for tlg0551.tlg002 I changed the title of the work to Greek from English (Kings), is this something you have been doing in general?

### CODE REVIEW

**Comment by AlisonBabeu** [comment]
Work on #1265.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5419)*

**Comment by lcerrato** [comment]
@AlisonBabeu 
When the Greek appears on the book title page, it is changed in the file itself, and the cts edition label only. I don't change the cts title to Greek.
And when the Greek is changed, I don't use all caps.

**Comment by lcerrato** [comment]
I confess I always thought that everything in the Roman History was one work, so I don't know it ended up split.

**Comment by AlisonBabeu** [comment]
Hi @lcerrato I guess we just followed the TLG in breaking it up. I"ll change the Greek title back to the English title in the CTS  file.  To further complicate matters the TLG uses Latin titles for this work its Basilica (Fragmenta). Do the changes to the rest of the headers, the CTS files, and bibliographic information look all right?

**Review by lcerrato — CHANGES_REQUESTED** [review]

**Comment by lcerrato** [comment]
@AlisonBabeu You don't have to follow the TLG on the Latin title if you cataloged the English. I think we should use English when we know it.

**Comment by AlisonBabeu** [comment]
Hi @lcerrato I've made the requested changes and will follow this pattern while I update the other Appian headers.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5421)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5422)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5424)*

**Review by lcerrato — APPROVED** [review]

**Pull request merged**
