### PR TITLE
DITTO L to CTS

### PR DESCRIPTION
**Pull request by PonteIneptique**
**I'd prefer it not to be merged right now**

I heard you liked tragedies and lines...

Logs :
- Done through github api and research on "<step refunit="line" from="DESCENDANT (1 L N%1)" to="DITTO"/>"
- Automatically transormed with https://github.com/PonteIneptique/automatic-github/blob/master/lines.py
- CTS metadata from Catalog

### CODE REVIEW

**Comment by PonteIneptique** [comment]
@srdee @balmas This PR needs to be checked (mostly \_\_cts\_\_.xml over written or stuff like that). I think for texts it should be ok...

**Comment by PonteIneptique** [comment]
@srdee @balmas Reason why not merged : I want to have a go with testing it with current Hook

**Comment by balmas** [comment]
@PonteIneptique 
check out
https://github.com/PerseusDL/canonical-greekLit/blob/lines-tragedy/data/tlg0006/tlg008/tlg0006.tlg008.perseus-grc1.xml#L284
vs
https://github.com/PerseusDL/canonical-greekLit/blob/master/data/tlg0006/tlg008/tlg0006.tlg008.perseus-grc1.xml#L326

Line number changed by script. The script should check to be sure it isn't changing an existing line # and if it is, it needs to report an error and flag for manual review.  Causes could be many. E.g. see 
https://github.com/PerseusDL/canonical/issues/95

**Comment by balmas** [comment]
Also see relevant issue https://github.com/PerseusDL/canonical/issues/145

**Comment by balmas** [comment]
Also re refsDecl, can we automatically fixup language ident codes to use 3 char code for greek and latin (grc and lat) instead of greek and latin?

**Comment by PonteIneptique** [comment]
**greek and lat -> grc and lat** That's a general script that should be run on the whole repo to deal with this.

**numbering issue** Mostly due to concurrent line numbering. For this precise file, see http://remacle.org/bloodwolf/tragediens/euripide/suppliantes.htm 78β and 86β and http://www.loebclassics.com/view/euripides-suppliant_women/1998/pb_LCL009.19.xml

**Comment by lcerrato** [comment]
I don't follow the line number question here. We should be following the Murray OUP. 
Looks like there are line numbering issues that start back at l 45? Not sure what is happening beginning with that chorus, but there are problems there.
I see significant textual differences with the LCL in lines 72 -86 ff but I'm not sure how those are relevant to the numbering issue highlighted above, since we aren't using LCL.  think the numbering goes awry earlier than that.

**Pull request closed without merging**
