### PR TITLE
(tlg0007.tlg070.perseus-grc1.xml) EpiDoc and CTS conversion

### LINKED ISSUE #588: (tlg0007.tlg070.perseus-grc1.xml) EpiDoc and CTS conversion
Claiming file for conversion work

### PR DESCRIPTION
**Pull request by Ethan-DR**
fix #588 
edited file for CTS and EpiDoc compliance

### CODE REVIEW

**Comment by lcerrato** [comment]
@Ethan-DR 
This won't fully pass unless a cts work file is found. Is there one created on another branch perhaps?

**Comment by Ethan-DR** [comment]
@lcerrato 
Ah I see. I'll create a CTS file now. Would it be okay to add that file to this branch or should I do it separately? 

Also, just to clarify, for any given set of files should we always make sure to first submit a cts workfile before we submit any of the greek or english files we've converted?

**Comment by lcerrato** [comment]
@Ethan-DR 
You may add it to this branch or just do a separate one. I can always hold any PRs until the work file is created, but doing the work file first is always better. 

First, it forces us to check the file names, titles, bibliographic information in the header and so forth, for any inconsistencies. Otherwise, is very easy to have files named differently in different locations.

Second, it enables the text files to pass the Hook tests. There needs to be a valid CTS work file checked in. Otherwise, the edition/translation files will always throw an error in the absence of a valid CTS work file. 

The CTS work file helps us spot naming inconsistencies (in case a file name was not bumped properly).

Remember to always pull from master each time you start a new branch. Otherwise, you can't easy cross check your work and there can be conflicts as a result.

**Comment by lcerrato** [comment]
@Ethan-DR 
Be careful — I see that the cts work file is using all caps. I will fix but this is incorrect.
Also the lang tags on the translations were incorrect.

**Comment by lcerrato** [comment]
I also see the top text tag is missing the lang attribute.

So far this is still failing the test even though I have pulled the work file into my local directory. I am not able to spot the issue causing the failure yet.

**Comment by Ethan-DR** [comment]
Ah okay, would you prefer that the text has the lang attribute instead of the or in addition to the div?

**Comment by lcerrato** [comment]
We use it in both places at Perseus. That is in the guidelines.

**Comment by lcerrato** [comment]
@Ethan-DR 
Thanks for your patience. Good work!

**Pull request merged**
