### PR TITLE
tlg0032.tlg001

### LINKED ISSUE #120: (tlg0032.tlg001) EpiDoc and CTS conversion

### PR DESCRIPTION
**Pull request by lcerrato**
fix #120

### CODE REVIEW

**Comment by lcerrato** [comment]
@balmas this fixes quotes in tlg0032.tlg002 eng as well; went back over those

**Comment by PonteIneptique** [comment]
Do you want me to check this PR @lcerrato ?

**Comment by balmas** [comment]
I would be very happy if you would @PonteIneptique

**Comment by lcerrato** [comment]
@TDBuck @PonteIneptique @balmas I'm happy for anyone to take a look -- no rush.

**Comment by PonteIneptique** [comment]
Seems fine to me @lcerrato . The only thing I would probably ask before merge is to lower caps the level name (Book->book) in cRefPattern if you're okay with that ?

**Comment by PonteIneptique** [comment]
Actually, could you open also an issue for the 002 you corrected ?

**Comment by lcerrato** [comment]
Sorry, I'm on some other projects at present. Let me close and reopen this when I have the chance to revisit.

**Pull request closed without merging**
