### PR TITLE
(typo correx) tlg0003 and tlg0010

### PR DESCRIPTION
**Pull request by lcerrato**
changes to headers and printing dates

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |  -150163 |
| `grc`     |  +150163 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/3552)*

**Comment by sonofmun** [comment]
The problem here is also not the version of Python (i.e., 3.5.4 instead of 3.5.3) since it works with both versions on my computer. I need to do some more investigation to see what is going on. For now, I will set the travis_wait again, which is the only way I have gotten it to work up to this point.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |  -150163 |
| `grc`     |  +150163 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/3554)*

**Comment by lcerrato** [comment]
Thanks for all of the work on this @sonofmun 

I appreciate it!

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |  -150163 |
| `grc`     |  +150163 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/3557)*

**Comment by lcerrato** [comment]
Ok, this is working (!) but I can't see full logs.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |  -150163 |
| `grc`     |  +150163 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/3558)*

**Comment by sonofmun** [comment]
I know. They changed something with Travis last week and it cuts the logs off. I have added my name to the issue on Travis that is reporting this and we will see what happens. If you need to know about a specific text, I can run Hook locally and get results for you from that. Just let me know.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |  -150163 |
| `grc`     |  +150163 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/3560)*

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `texts_passing` |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `UNK`     |  -150163 |
| `grc`     |  +150163 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/PerseusDL/canonical-greekLit/3565)*

**Pull request merged**
